steps:
  publish:
    image: eclipse-temurin:25-jdk
    when:
      - event: manual
    environment:
      ORG_GRADLE_PROJECT_mavenCentralUsername:
        from_secret: MAVEN_CENTRAL_USERNAME
      ORG_GRADLE_PROJECT_mavenCentralPassword:
        from_secret: MAVEN_CENTRAL_PASSWORD
      ORG_GRADLE_PROJECT_signingInMemoryKey:
        from_secret: GPG_MAVEN_CENTRAL_PRIVATE_KEY
      ORG_GRADLE_PROJECT_signingInMemoryKeyId:
        from_secret: GPG_MAVEN_CENTRAL_PRIVATE_KEY_ID
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword:
        from_secret: GPG_MAVEN_CENTRAL_PRIVATE_KEY_PASSWORD
      MODULE_TO_PUBLISH: "NONE"
    commands:
      - |
        if [ -z "$MODULE_TO_PUBLISH" ] || [ "$MODULE_TO_PUBLISH" = "NONE" ]; then
          echo "ERROR: You must provide a MODULE_TO_PUBLISH parameter when triggering manually."
          exit 1
        fi
      - ./gradlew clean ":$MODULE_TO_PUBLISH:publishToMavenCentral" --no-configuration-cachecache